DATA_INICIO#25/03/2025 19:45:12
COMANDO#/home/producao/KENAN/py/ALGAR_PRD_ExecGen.py -P KENAN_MODULOCARTAODECREDITO_CANCELA
================================================================================

25/03/2025-19:45:13 INICIO - Sistema..: KENAN
                    INICIO - Script...: ALGAR_PRD_ExecGen_KENAN_MODULOCARTAODECREDITO_CANCELA
                    --------------------------------------------------------------------------------
25/03/2025-19:45:14    [E] Criando lock
25/03/2025-19:45:14        [I] Lock criado
25/03/2025-19:45:14    [E] ETAPA << EXECUTAR PROCESSO >> :: INICIANDO
25/03/2025-19:45:14        [E] Executando processo generico => KENAN_MODULOCARTAODECREDITO_CANCELA
25/03/2025-19:45:14        [E] Iniciando configuracao do processo KENAN_MODULOCARTAODECREDITO_CANCELA
25/03/2025-19:45:14            [I] Preparando sequencia de etapas a executar
25/03/2025-19:45:14            [I] Lista de etapas a executar: ['EXECUTA JAVA', 'BUSCA_ARQS', 'ENVIA_ARQS_PAGTEL', 'ENVIA_ARQS_PUBLIC']
25/03/2025-19:45:14            [I] Processo PERSISTENTE. Mantendo residuos de execucao anterior
25/03/2025-19:45:14        [E] Iniciando configuracao das etapas do processo KENAN_MODULOCARTAODECREDITO_CANCELA
25/03/2025-19:45:14            [I] Etapas configuradas
25/03/2025-19:45:14        [E] Iniciando execucao do processo
25/03/2025-19:45:14        [E] Iniciando execucao da etapa EXECUTA JAVA
25/03/2025-19:45:14            [E] [ ETAPA: EXECUTA JAVA ] Iniciando instancias da etapa
25/03/2025-19:45:15            [E] [ ETAPA: EXECUTA JAVA ] Iniciando execucao
/home/producao/Python/Python3/lib/python3.7/site-packages/paramiko/transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  \"class\": algorithms.Blowfish,
25/03/2025-19:45:15            [E] [ ETAPA: EXECUTA JAVA - JOB :EXECUTA ] Iniciando execucao
25/03/2025-19:45:15                [E] [ ETAPA: EXECUTA JAVA - JOB :EXECUTA ] Executando java.executa_java.executa_java
25/03/2025-19:45:15                [E] Executando comando JAVA : -jar /home/producao/KENAN/py/Java/CartaoCredito/ModuloCartaoCredito.jar 'CANCELAMENTO'
25/03/2025-19:45:15                    [I] comando java completo : /usr/bin/java -jar /home/producao/KENAN/py/Java/CartaoCredito/ModuloCartaoCredito.jar 'CANCELAMENTO' ModuloCartaoCredito_CANCELA_20250325194514.log  /workprod/FXPRD/log/ 
25/03/2025-19:45:30                    [I] Java executado com return code = 0
25/03/2025-19:46:09                [A] ARQUIVO < /workprod/FXPRD/log/ModuloCartaoCredito_CANCELA_20250325194514.log >
25/03/2025-19:46:09                [A] ----------------------------------------------------------------------------------------------------
25/03/2025-19:46:09                [A]                                     ROTINAS - CARTAO DE CREDITO
25/03/2025-19:46:09                [A] ----------------------------------------------------------------------------------------------------
25/03/2025-19:46:09                [A] INICIO                                       : 25/03/2025 19:45:15
25/03/2025-19:46:09                [A] ----------------------------------------------------------------------------------------------------
25/03/2025-19:46:09                [A] TIPO DE EXECUCAO                             : CANCELAMENTO
25/03/2025-19:46:09                [A] ----------------------------------------------------------------------------------------------------
25/03/2025-19:46:09                [A] BANCO DE DADOS                               : FXPRD
25/03/2025-19:46:09                [A] USUARIO                                      : PRODUCAO
25/03/2025-19:46:09                [A] VERSAO DA APLICACAO                          : 2.0
25/03/2025-19:46:09                [A] VERSAO DO JAVA                               : 1.8
25/03/2025-19:46:09                [A] ----------------------------------------------------------------------------------------------------
25/03/2025-19:46:09                [A] CONECTANDO AO BANCO DE DADOS...
25/03/2025-19:46:09                [A] BANCO CONECTADO COM SUCESSO!
25/03/2025-19:46:09                [A] 
25/03/2025-19:46:09                [A] ----------------------------------------------------------------------------------------------------
25/03/2025-19:46:09                [A] CARTAO DE CREDITO - GERACAO DE ARQUIVO - CANCELAMENTO DE FATURAS
25/03/2025-19:46:09                [A] ----------------------------------------------------------------------------------------------------
25/03/2025-19:46:09                [A] DIRETORIO DESTINO ARQUIVO                    : /workprod/FXPRD/data/arrecada/ccredito/cancelamento
25/03/2025-19:46:09                [A] GATEWAY                                      : M4U
25/03/2025-19:46:09                [A] INVOICE_TYPE                                 : 1
25/03/2025-19:46:09                [A] ----------------------------------------------------------------------------------------------------
25/03/2025-19:46:09                [A] NAO EXISTEM FATURAS PENDENTES DE ENVIO PARA ESTA EMPRESA/ADQUIRENTE - FINALIZANDO O PROCESSO
25/03/2025-19:46:09                [A] 
25/03/2025-19:46:09                [A] ----------------------------------------------------------------------------------------------------
25/03/2025-19:46:09                [A] CARTAO DE CREDITO - GERACAO DE ARQUIVO - CANCELAMENTO DE FATURAS
25/03/2025-19:46:09                [A] ----------------------------------------------------------------------------------------------------
25/03/2025-19:46:09                [A] DIRETORIO DESTINO ARQUIVO                    : /workprod/FXPRD/data/arrecada/ccredito/cancelamento
25/03/2025-19:46:09                [A] GATEWAY                                      : M4U
25/03/2025-19:46:09                [A] INVOICE_TYPE                                 : 2
25/03/2025-19:46:09                [A] ----------------------------------------------------------------------------------------------------
25/03/2025-19:46:09                [A] NAO EXISTEM FATURAS PENDENTES DE ENVIO PARA ESTA EMPRESA/ADQUIRENTE - FINALIZANDO O PROCESSO
25/03/2025-19:46:09                [A] 
25/03/2025-19:46:09                [A] ----------------------------------------------------------------------------------------------------
25/03/2025-19:46:09                [A] CARTAO DE CREDITO - GERACAO DE ARQUIVO - CANCELAMENTO DE FATURAS
25/03/2025-19:46:09                [A] ----------------------------------------------------------------------------------------------------
25/03/2025-19:46:09                [A] DIRETORIO DESTINO ARQUIVO                    : /workprod/FXPRD/data/arrecada/ccredito/cancelamento
25/03/2025-19:46:09                [A] GATEWAY                                      : M4U
25/03/2025-19:46:09                [A] INVOICE_TYPE                                 : 4
25/03/2025-19:46:09                [A] ----------------------------------------------------------------------------------------------------
25/03/2025-19:46:09                [A] NAO EXISTEM FATURAS PENDENTES DE ENVIO PARA ESTA EMPRESA/ADQUIRENTE - FINALIZANDO O PROCESSO
25/03/2025-19:46:09                [A] 
25/03/2025-19:46:09                [A] ----------------------------------------------------------------------------------------------------
25/03/2025-19:46:09                [A] CARTAO DE CREDITO - GERACAO DE ARQUIVO - CANCELAMENTO DE FATURAS
25/03/2025-19:46:09                [A] ----------------------------------------------------------------------------------------------------
25/03/2025-19:46:09                [A] DIRETORIO DESTINO ARQUIVO                    : /workprod/FXPRD/data/arrecada/ccredito/cancelamento
25/03/2025-19:46:09                [A] GATEWAY                                      : PGT
25/03/2025-19:46:09                [A] INVOICE_TYPE                                 : 1
25/03/2025-19:46:09                [A] ----------------------------------------------------------------------------------------------------
25/03/2025-19:46:09                [A] NAO EXISTEM FATURAS PENDENTES DE ENVIO PARA ESTA EMPRESA/ADQUIRENTE - FINALIZANDO O PROCESSO
25/03/2025-19:46:09                [A] 
25/03/2025-19:46:09                [A] ----------------------------------------------------------------------------------------------------
25/03/2025-19:46:09                [A] CARTAO DE CREDITO - GERACAO DE ARQUIVO - CANCELAMENTO DE FATURAS
25/03/2025-19:46:09                [A] ----------------------------------------------------------------------------------------------------
25/03/2025-19:46:09                [A] DIRETORIO DESTINO ARQUIVO                    : /workprod/FXPRD/data/arrecada/ccredito/cancelamento
25/03/2025-19:46:09                [A] GATEWAY                                      : PGT
25/03/2025-19:46:09                [A] INVOICE_TYPE                                 : 4
25/03/2025-19:46:09                [A] ----------------------------------------------------------------------------------------------------
25/03/2025-19:46:09                [A] NAO EXISTEM FATURAS PENDENTES DE ENVIO PARA ESTA EMPRESA/ADQUIRENTE - FINALIZANDO O PROCESSO
25/03/2025-19:46:09                [A] ----------------------------------------------------------------------------------------------------
25/03/2025-19:46:09                [A] FIM                                          : 25/03/2025 19:45:28
25/03/2025-19:46:09                [A] ----------------------------------------------------------------------------------------------------
25/03/2025-19:46:09                [A] STATUS#OK
25/03/2025-19:46:09                    [I] Java executado com sucesso
25/03/2025-19:46:09                    [I] [ ETAPA: EXECUTA JAVA - JOB :EXECUTA ] Executado
25/03/2025-19:46:09                    [I] [ ETAPA: EXECUTA JAVA - JOB :EXECUTA ] Instancia 0 => finalizado com status :: 0
25/03/2025-19:45:16                [I] [ ETAPA: EXECUTA JAVA ] Instancias iniciadas
25/03/2025-19:45:16                [I] [ ETAPA: EXECUTA JAVA ] Aguardando instancias finalizarem
25/03/2025-19:46:09                [I] [ ETAPA: EXECUTA JAVA ] Instancias finalizaram
25/03/2025-19:46:09                [I] [ ETAPA: EXECUTA JAVA ] Instancia - 1_0 = SUCESSO
25/03/2025-19:46:09            [I] Etapa EXECUTA JAVA finalizada com SUCESSO
25/03/2025-19:46:10        [E] Iniciando execucao da etapa BUSCA_ARQS
25/03/2025-19:46:10            [E] [ ETAPA: BUSCA_ARQS ] Iniciando instancias da etapa
25/03/2025-19:46:11            [E] [ ETAPA: BUSCA_ARQS ] Iniciando execucao
25/03/2025-19:46:11            [E] Iniciando transferencia da(s) mascara(s) ['Fat_*.can']
25/03/2025-19:46:11                    [I] Nao haviam arquivos para transferir. ABORTAR em caso de nao haver arquivos = False
25/03/2025-19:46:12                [I] [ ETAPA: BUSCA_ARQS ] Instancias iniciadas
25/03/2025-19:46:12                [I] [ ETAPA: BUSCA_ARQS ] Aguardando instancias finalizarem
25/03/2025-19:46:12                [I] [ ETAPA: BUSCA_ARQS ] Instancias finalizaram
25/03/2025-19:46:12                [I] [ ETAPA: BUSCA_ARQS ] Instancia - 1_0 = SUCESSO
25/03/2025-19:46:12            [I] Etapa BUSCA_ARQS finalizada com SUCESSO
25/03/2025-19:46:13        [E] Iniciando execucao da etapa ENVIA_ARQS_PAGTEL
25/03/2025-19:46:13            [E] [ ETAPA: ENVIA_ARQS_PAGTEL ] Iniciando instancias da etapa
25/03/2025-19:46:14            [E] [ ETAPA: ENVIA_ARQS_PAGTEL ] Iniciando execucao
25/03/2025-19:46:14            [E] Iniciando transferencia da(s) mascara(s) ['Fat_*.can']
25/03/2025-19:48:21                [EXCECAO]------------------------------------------------------------------------------------------------------------------------
                                   [EXCECAO] conexao.rede.sftp :  > Traceback (most recent call last):
                                   [EXCECAO] conexao.rede.sftp :  >   File \"/home/producao/pyApiAlgar/PRD/api/rede/sftp.py\", line 106, in conecta
                                   [EXCECAO] conexao.rede.sftp :  >      self.__transport = paramiko.Transport((self.servidor, self.porta))
                                   [EXCECAO] conexao.rede.sftp :  >   File \"/home/producao/Python/Python3/lib/python3.7/site-packages/paramiko/transport.py\", line 416, in __init__
                                   [EXCECAO] conexao.rede.sftp :  >      \"Unable to connect to {}: {}\".format(hostname, reason)
                                   [EXCECAO] conexao.rede.sftp :  > paramiko.ssh_exception.SSHException: Unable to connect to 10.202.62.98: [Errno 110] Connection timed out
                                   [EXCECAO]------------------------------------------------------------------------------------------------------------------------
25/03/2025-19:51:29                [EXCECAO]------------------------------------------------------------------------------------------------------------------------
                                   [EXCECAO] conexao.rede.sftp :  > Traceback (most recent call last):
                                   [EXCECAO] conexao.rede.sftp :  >   File \"/home/producao/pyApiAlgar/PRD/api/rede/sftp.py\", line 106, in conecta
                                   [EXCECAO] conexao.rede.sftp :  >      self.__transport = paramiko.Transport((self.servidor, self.porta))
                                   [EXCECAO] conexao.rede.sftp :  >   File \"/home/producao/Python/Python3/lib/python3.7/site-packages/paramiko/transport.py\", line 416, in __init__
                                   [EXCECAO] conexao.rede.sftp :  >      \"Unable to connect to {}: {}\".format(hostname, reason)
                                   [EXCECAO] conexao.rede.sftp :  > paramiko.ssh_exception.SSHException: Unable to connect to 10.202.62.98: [Errno 110] Connection timed out
                                   [EXCECAO]------------------------------------------------------------------------------------------------------------------------
25/03/2025-19:54:36                [EXCECAO]------------------------------------------------------------------------------------------------------------------------
                                   [EXCECAO] conexao.rede.sftp :  > Traceback (most recent call last):
                                   [EXCECAO] conexao.rede.sftp :  >   File \"/home/producao/pyApiAlgar/PRD/api/rede/sftp.py\", line 106, in conecta
                                   [EXCECAO] conexao.rede.sftp :  >      self.__transport = paramiko.Transport((self.servidor, self.porta))
                                   [EXCECAO] conexao.rede.sftp :  >   File \"/home/producao/Python/Python3/lib/python3.7/site-packages/paramiko/transport.py\", line 416, in __init__
                                   [EXCECAO] conexao.rede.sftp :  >      \"Unable to connect to {}: {}\".format(hostname, reason)
                                   [EXCECAO] conexao.rede.sftp :  > paramiko.ssh_exception.SSHException: Unable to connect to 10.202.62.98: [Errno 110] Connection timed out
                                   [EXCECAO]------------------------------------------------------------------------------------------------------------------------
25/03/2025-19:57:43                [EXCECAO]------------------------------------------------------------------------------------------------------------------------
                                   [EXCECAO] conexao.rede.sftp :  > Traceback (most recent call last):
                                   [EXCECAO] conexao.rede.sftp :  >   File \"/home/producao/pyApiAlgar/PRD/api/rede/sftp.py\", line 106, in conecta
                                   [EXCECAO] conexao.rede.sftp :  >      self.__transport = paramiko.Transport((self.servidor, self.porta))
                                   [EXCECAO] conexao.rede.sftp :  >   File \"/home/producao/Python/Python3/lib/python3.7/site-packages/paramiko/transport.py\", line 416, in __init__
                                   [EXCECAO] conexao.rede.sftp :  >      \"Unable to connect to {}: {}\".format(hostname, reason)
                                   [EXCECAO] conexao.rede.sftp :  > paramiko.ssh_exception.SSHException: Unable to connect to 10.202.62.98: [Errno 110] Connection timed out
                                   [EXCECAO]------------------------------------------------------------------------------------------------------------------------
25/03/2025-19:57:43                [EXCECAO]------------------------------------------------------------------------------------------------------------------------
                                   [EXCECAO] api.rede.sftp : SFTP > Traceback (most recent call last):
                                   [EXCECAO] api.rede.sftp : SFTP >   File \"/home/producao/pyApiAlgar/PRD/api/rede/sftp.py\", line 106, in conecta
                                   [EXCECAO] api.rede.sftp : SFTP >      self.__transport = paramiko.Transport((self.servidor, self.porta))
                                   [EXCECAO] api.rede.sftp : SFTP >   File \"/home/producao/Python/Python3/lib/python3.7/site-packages/paramiko/transport.py\", line 416, in __init__
                                   [EXCECAO] api.rede.sftp : SFTP >      \"Unable to connect to {}: {}\".format(hostname, reason)
                                   [EXCECAO] api.rede.sftp : SFTP > paramiko.ssh_exception.SSHException: Unable to connect to 10.202.62.98: [Errno 110] Connection timed out
                                   [EXCECAO]------------------------------------------------------------------------------------------------------------------------
25/03/2025-19:57:43                [EXCECAO]------------------------------------------------------------------------------------------------------------------------
                                   [EXCECAO] mods.generico.transferencia : Transferencia > Traceback (most recent call last):
                                   [EXCECAO] mods.generico.transferencia : Transferencia >   File \"/home/producao/pyApiAlgar/PRD/api/base.py\", line 18, in funcaoNova
                                   [EXCECAO] mods.generico.transferencia : Transferencia >      ret = funcao(self, *args, **kwargs)
                                   [EXCECAO] mods.generico.transferencia : Transferencia >   File \"/home/producao/pyApiAlgar/PRD/mods/generico/transferencia.py\", line 234, in run
                                   [EXCECAO] mods.generico.transferencia : Transferencia >      ret = self.por_rede()
                                   [EXCECAO] mods.generico.transferencia : Transferencia >   File \"/home/producao/pyApiAlgar/PRD/mods/generico/transferencia.py\", line 386, in por_rede
                                   [EXCECAO] mods.generico.transferencia : Transferencia >      self._cnx_atual = self.conecta_remoto()
                                   [EXCECAO] mods.generico.transferencia : Transferencia >   File \"/home/producao/pyApiAlgar/PRD/mods/generico/transferencia.py\", line 381, in conecta_remoto
                                   [EXCECAO] mods.generico.transferencia : Transferencia >      cnx = api_rede.conectarSFTP(def_cnx)
                                   [EXCECAO] mods.generico.transferencia : Transferencia >   File \"/home/producao/pyApiAlgar/PRD/api/rede/__init__.py\", line 4, in conectarSFTP
                                   [EXCECAO] mods.generico.transferencia : Transferencia >      return sftp.SFTP(defCnx.hst, defCnx.usr, defCnx.pwd, defCnx.porta)
                                   [EXCECAO] mods.generico.transferencia : Transferencia >   File \"/home/producao/pyApiAlgar/PRD/api/rede/sftp.py\", line 83, in __init__
                                   [EXCECAO] mods.generico.transferencia : Transferencia >      self.conecta()
                                   [EXCECAO] mods.generico.transferencia : Transferencia >   File \"/home/producao/pyApiAlgar/PRD/api/rede/sftp.py\", line 106, in conecta
                                   [EXCECAO] mods.generico.transferencia : Transferencia >      self.__transport = paramiko.Transport((self.servidor, self.porta))
                                   [EXCECAO] mods.generico.transferencia : Transferencia >   File \"/home/producao/Python/Python3/lib/python3.7/site-packages/paramiko/transport.py\", line 416, in __init__
                                   [EXCECAO] mods.generico.transferencia : Transferencia >      \"Unable to connect to {}: {}\".format(hostname, reason)
                                   [EXCECAO] mods.generico.transferencia : Transferencia > paramiko.ssh_exception.SSHException: Unable to connect to 10.202.62.98: [Errno 110] Connection timed out
                                   [EXCECAO]------------------------------------------------------------------------------------------------------------------------
Process Process-6:
Traceback (most recent call last):
  File \"/home/producao/Python/Python3/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap
    self.run()
  File \"/home/producao/Python/Python3/lib/python3.7/multiprocessing/process.py\", line 99, in run
    self._target(*self._args, **self._kwargs)
  File \"/home/producao/pyApiAlgar/PRD/mods/generico/executor.py\", line 254, in run
    ret_dict[f\"{self.mod}_{self.rst}\"] = proc.run(self.mod, self.rst)
  File \"/home/producao/pyApiAlgar/PRD/api/base.py\", line 18, in funcaoNova
    ret = funcao(self, *args, **kwargs)
  File \"/home/producao/pyApiAlgar/PRD/mods/generico/transferencia.py\", line 234, in run
    ret = self.por_rede()
  File \"/home/producao/pyApiAlgar/PRD/mods/generico/transferencia.py\", line 386, in por_rede
    self._cnx_atual = self.conecta_remoto()
  File \"/home/producao/pyApiAlgar/PRD/mods/generico/transferencia.py\", line 381, in conecta_remoto
    cnx = api_rede.conectarSFTP(def_cnx)
  File \"/home/producao/pyApiAlgar/PRD/api/rede/__init__.py\", line 4, in conectarSFTP
    return sftp.SFTP(defCnx.hst, defCnx.usr, defCnx.pwd, defCnx.porta)
  File \"/home/producao/pyApiAlgar/PRD/api/rede/sftp.py\", line 83, in __init__
    self.conecta()
  File \"/home/producao/pyApiAlgar/PRD/api/rede/sftp.py\", line 106, in conecta
    self.__transport = paramiko.Transport((self.servidor, self.porta))
  File \"/home/producao/Python/Python3/lib/python3.7/site-packages/paramiko/transport.py\", line 416, in __init__
    \"Unable to connect to {}: {}\".format(hostname, reason)
paramiko.ssh_exception.SSHException: Unable to connect to 10.202.62.98: [Errno 110] Connection timed out
25/03/2025-19:46:15                [I] [ ETAPA: ENVIA_ARQS_PAGTEL ] Instancias iniciadas
25/03/2025-19:46:15                [I] [ ETAPA: ENVIA_ARQS_PAGTEL ] Aguardando instancias finalizarem
25/03/2025-19:57:43                [I] [ ETAPA: ENVIA_ARQS_PAGTEL ] Instancias finalizaram
25/03/2025-19:57:43                [I] [ ETAPA: ENVIA_ARQS_PAGTEL ] Instancia - 1_0 = ERRO
25/03/2025-19:57:43            [ERRO]############################################################
                               [ERRO] Etapa ENVIA_ARQS_PAGTEL finalizada com ERRO
                               [ERRO]############################################################
25/03/2025-19:57:43            [I] ETAPA << EXECUTAR PROCESSO >> :: ERRO
25/03/2025-19:57:43 EMAIL ERRO .....: ['eduardog@algartelecom.com.br', 'alvina.ferreira@algartelecom.com.br', 'conciliacaofinanceira@algartelecom.com.br', 'abadio.cesar@algartelecom.com.br']
25/03/2025-19:57:43 --------------------------------------------------------------------------------
                    FIM :: STATUS .....: ERRO

================================================================================
DATA_FIM#25/03/2025 19:57:47
STATUS#ERRO

